name: Build Firmware

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: thumbv7em-none-eabihf
        components: llvm-tools-preview

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Cache target directory
      uses: actions/cache@v4
      with:
        path: target/
        key: ${{ runner.os }}-target-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-target-

    - name: Install cargo-make
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-make

    - name: Install flip-link
      uses: taiki-e/install-action@v2
      with:
        tool: flip-link

    - name: Install cargo-binutils
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-binutils

    - name: Install cargo-hex-to-uf2
      run: cargo install cargo-hex-to-uf2

    - name: Build firmware and generate UF2 files
      run: cargo make uf2

    - name: Upload combined firmware
      uses: actions/upload-artifact@v4
      with:
        name: dactyl-firmware
        path: |
          left.uf2
          right.uf2
        retention-days: 30
